// Generated by CoffeeScript 1.12.4
(function() {
  var getCurrentTime, mp4, mp4file;

  mp4 = require('../mp4');

  getCurrentTime = function() {
    var time;
    time = process.hrtime();
    return time[0] + time[1] / 1e9;
  };

  if (process.argv.length < 3) {
    console.log("Error: specify an mp4 filename");
    return 1;
  }

  mp4file = new mp4.MP4File(process.argv[2]);

  mp4file.parse();

  mp4file.dump();

}).call(this);
